### ISSUE TITLE
Docker: hide behind vpn container and access webui

### ISSUE THREAD

**Issue by niawag** [anthonyraymond/joal#132]
Hi and thanks a lot for this great piece of code !

I'm using it on a Pi3 and it's working great but I'd like to be able to hide it behind a VPN, also dockerized, on the same Pi. I'm not a docker expert but I've read a bit a came up to this config: 
```
  joal:
    container_name: joal
    image: anthonyraymond/joal:2.1.24-arm
    restart: unless-stopped
    network_mode: service:transvpn
    volumes:
      - /home/pi/dockers/joal:/data
#    ports:
#      - 6969:6969 --> had to womment these out for network_mode to work
    command: (...)

  transvpn:
    container_name: transvpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - lots of stuff
    volumes:
      - (...)
    ports:
      - 9091:9091
      - 7779:7779
      - 6969:6969 # for joal
    logging:
      driver: json-file
      options:
          max-size: 10m
    restart: unless-stopped
```

Joal has the VPN IP (hooray) but I can't connect to the webUI.  I tried by adding the Joal port (6969) to the vpn container but it's not working.

Do you know how I could achieve this ?
