### ISSUE TITLE
Issue with UI

### ISSUE THREAD

**Issue by Eliesemoule** [anthonyraymond/joal#144]
Hello,

I have a problem. I can't configure the UI.
I clicked on "Change connection settings" and filled in the four fields. But I still get the message "Failed to connect to JOA, retry in 8 seconds". I use Docker 20.10.8 on CentOS 8. Here is my docker-compose :
```
---
version: "3.7"
services:
  faketorrents:
    container_name: faketorrents
    image: anthonyraymond/joal:2.1.24
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=80", "--joal
.ui.path.prefix=faketorrents", "--joal.ui.secret-token=JR2y4gmuL9Mk7CMDM2nCdwW2"]
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - '80:80'
```
At the firewall level, I have only opened port 80

Could you please help me. Thanks
