### ISSUE TITLE
Docker: can't acces webui behind a VPN container

### ISSUE THREAD

**Issue by Cosmonear** [anthonyraymond/joal#168]
Hello, 
First, thank you very much for the work and the app.

I have approximately the same issue as #132 
I use arch-delugevpn.

Here are my docker-compose files :
```
---
version: "2.1"
services:
  arch-delugevpn:
    image: binhex/arch-delugevpn
    container_name: arch-delugevpn
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=custom
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=PPPPPPP...
    volumes:
      - stuff...
    ports:
      - 58846:58846
      - 58946:58946
      - 8112:8112 #deluge ui
      - 8118:8118 #proxy
      - XXXX:XXXX#joal
    restart: unless-stopped
    networks:
      - networka
    cap_add:
      - NET_ADMIN

networks:
    networka:
        external: true

---
version: "2"
services:
  joal:
    image: anthonyraymond/joal
    container_name: joal
    restart: unless-stopped
    volumes:
      - ./joal-data:/data
    user: 1000:1000
    labels:
      - com.centurylinklabs.watchtower.enable=true
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=XXXX", "--joal.ui.path.prefix=YYY", "--joal.ui.secret-token=ZZZ"]
    network_mode: "container:arch-delugevpn"

```

I cannot access the UI of Joal with ` network_mode: "container:arch-delugevpn"` but joal has the same IP of the VPN (that I want).
I can only access the UI of Joal only without the `network_mode: "container:arch-delugevpn"` but it will not have the IP of the VPN.

I don't understand why. If someone can help me.
Thanks.
