### ISSUE TITLE
Access to web-ui with swag and dperson-vpn

### ISSUE THREAD

**Issue by XamYp** [anthonyraymond/joal#183]
Hello,

I'm trying to access the web interface from my swag reverse proxy but it doesn't work. I had seen this post but it is not implementable for me: [issues-49](https://github.com/anthonyraymond/joal/issues/49)

I'm using portainer and my stack configuration is as follows:

```yaml
version: '3.7'
services:
 vpn:
  container_name: vpn
  image: dperson/openvpn-client
  restart: always
  devices:
    - /dev/net/tun
  cap_add:
    - NET_ADMIN
  volumes:
    - /home/docker/vpn/openvpn:/vpn:ro
  dns:
    - "1.1.1.1"
    - "8.8.8.8"
    - "8.8.4.4"
  environment:
    - FIREWALL
    - PUID=1001
    - GUID=1001
    - log=DEBUG
  ports:
    - "8081:8080"
      
 joal:
  depends_on:
    - vpn
  image: anthonyraymond/joal
  container_name: joal
  restart: unless-stopped
  network_mode: "service:vpn"
  volumes:
    - /home/docker/joal/data:/data
  environment:
   - PUID=1001
   - PGID=1001
   - TZ=Europe/Paris
  command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=8081", "--joal.ui.path.prefix=joal", "--joal.ui.secret-token=xxxxxxxxxxxx"]
```

An example of my swag joal.subdomain.conf file :

```conf
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name joal.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location /joal/ {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app joal;
        set $upstream_port 8081;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    # REMOVE THIS LINE BEFORE SUBMITTING: Some proxies require one or more additional location blocks for things like API or RPC endpoints.
    # REMOVE THIS LINE BEFORE SUBMITTING: If the proxy you are making a sample for does not require an additional location block please remove the commented out section below.
    # location ~ (/<container_name>)?/api {
    #     include /config/nginx/proxy.conf;
    #     include /config/nginx/resolver.conf;
    #     set $upstream_app <container_name>;
    #     set $upstream_port <port_number>;
    #     set $upstream_proto <http or https>;
    #     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    #
    #     # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
    # }
}
```
Do you have any idea what swag configuration I should use to access Joal's web interface please?
