### ISSUE TITLE
[ENHANCEMENT] Add variable

### ISSUE THREAD

**Issue by Nackophilz** [anthonyraymond/joal#197]
Hi!

First of all, thanks for your work!

Edit : For Docker Container
Nevertheless, I would have liked to know if it was possible to pass the post arguments of Joal in environment variable instead? It would be much simpler to configure and to maintain in case of change :)

It would help to make a template accessible to everyone ! :)

There is the option i suggest to took into variable:

--joal-conf
--spring.main.web-environment
--server.port
--joal.ui.path.prefix
--joal.ui.secret-token

**Comment by anthonyraymond** [comment]
You can't use environment variable ATM if this is what you are talking about.

But, you can use the docker-compose `.env` variable file to perform a similar result. (example here)[https://github.com/anthonyraymond/joal/wiki/Joal-&-VPN-&-qbittorrent-&-Reverse-proxy-(with-docker)]

**Comment by JourneyOver** [comment]
@anthonyraymond actually you can if that is what he is talking about, this is my current docker-compose file (albiet excluding a few things like network/hostname and a few extra env variables that I include in all my compose files) 

```yml
---
version: "3.8"

services:

  joal:
    image: docker.io/anthonyraymond/joal:latest
    container_name: joal
    restart: unless-stopped
    environment:
      - joal-conf=/data
      - spring.main.web-environment=true
      - server.port=${JOAL_SERVER_PORT}
      - joal.ui.path.prefix=${JOAL_PATH_PREFIX}
      - joal.ui.secret-token=${JOAL_SECRET_TOKEN}
    volumes:
      - /path/to/joal/data:/data
    ports:
      - ${JOAL_SERVER_PORT}:${JOAL_SERVER_PORT}/tcp
 ```

and everything works perfectly. So you technically can do away with the whole `command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=PORT", "--joal.ui.path.prefix=SECRET_OBFUSCATION_PATH", "--joal.ui.secret-token=SECRET_TOKEN"]` like you have in your example readme for your docker compose and just use environment variables instead.
