### ISSUE TITLE
Web UI error on Websocket

### ISSUE THREAD

**Issue by clementmoine** [anthonyraymond/joal#224]
Hello thank you for your work on this tool !

I installed the JOAL container in my docker (installed on a Raspberry Pi) with these settings :
```
    joal:
        image: anthonyraymond/joal:2.1.34
        container_name: joal
        restart: always
        volumes:
          - ${ROOT:-.}/config/joal:/data
        ports:
          - 9119:9119
        environment:
          - joal-conf=/data
          - spring.main.web-environment=true
          - server.port=9119
          - joal.ui.path.prefix=torrents
          - joal.ui.secret-token=Ee@ERg?FEFeFEd2
```

I tried setting torrents files under the config/joal/torrents. Everything looks good in logs :

```
joal  | [INFO ] 2023-10-26 11:12:09.356 [           main] c.t.t.c.Torrent: Multi-file torrent information:
joal  | [INFO ] 2023-10-26 11:12:09.357 [           main] c.t.t.c.Torrent:   Torrent name: Fantastic Beasts The Secrets of Dumbledore (2022)
joal  | [INFO ] 2023-10-26 11:12:09.358 [           main] c.t.t.c.Torrent:   Announced at:
joal  | [INFO ] 2023-10-26 11:12:09.359 [           main] c.t.t.c.Torrent:      1. https://www.sometorrenttracker/anon
joal  | [INFO ] 2023-10-26 11:12:09.360 [           main] c.t.t.c.Torrent:   Created on..: 2022-11-24T11:32:43.000+0000
joal  | [INFO ] 2023-10-26 11:12:09.363 [           main] c.t.t.c.Torrent:   Comment.....: Enjoy !
joal  | [INFO ] 2023-10-26 11:12:09.364 [           main] c.t.t.c.Torrent:   Created by..: SomeTorrentTracker
joal  | [INFO ] 2023-10-26 11:12:09.364 [           main] c.t.t.c.Torrent:   Found 2 file(s) in multi-file torrent structure.
joal  | [INFO ] 2023-10-26 11:12:09.366 [           main] c.t.t.c.Torrent:   Pieces......: 4989 piece(s) (1048576 byte(s)/piece)
joal  | [INFO ] 2023-10-26 11:12:09.367 [           main] c.t.t.c.Torrent:   Total size..: 5,231,230,970 byte(s)
```

So JOAL seems to work without issues, but when I try to access the webui `http://192.168.1.2:9119/torrents/ui` I am not prompted to enter a password or something, and my network tab says :

```
WebSocket connection to 'ws://192.168.1.2:9119/' failed: 
client @ webstomp.js:826
value @ JoalStompClient.ts:58
(anonyme) @ JoalStompClient.ts:131
JoalStompClient.ts:81 error message from websocket CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}
```

Am I doing something wrong ?

I am not in a specific kind of networking with VPN, Proxy or something, just JOAL installed on my RPI and me trying to connect from my laptop on the same home network.
