### ISSUE TITLE
HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by DrTableBasse** [anthonyraymond/joal#240]
Hey, 

Thx a lot for your project. It is good !

I get 404 when I started the docker compose file with this configuration : 

```yml
version: "2"
services:
  joal:
    image: anthonyraymond/joal:2.1.36
    container_name: joal
    restart: unless-stopped
    volumes:
      - ./config:/data
    ports:
      - 8114:8114
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=8114", "--joal.ui.path.prefix=test", "--joal.ui.secret-token=test"]
```

and with this config.json 

```json
{
  "minUploadRate": 30,
  "maxUploadRate": 170,
  "simultaneousSeed": 200,
  "client": "qbittorrent-4.6.5.client",
  "keepTorrentWithZeroLeechers": true,
  "uploadRatioTarget": -1.0
}
```

I really dont understand why it doesn't works :-/ 

Thx a lot !!
