### ISSUE TITLE
Steps to run the container behind a vpn

### ISSUE THREAD

**Issue by julien-vu** [anthonyraymond/joal#94]
Hi, as the title state it, I would like to know how would you run the docker container with a nord or open vpn ?
Thanks !

**Comment by anthonyraymond** [comment]
Hi,
my service runs on a raspberry, so use a armhf architecture for my openvpn image but you should probably be able to adapt if you are running on x86

I use something similar to this as my docker-compose:

```
version: '3.7'

services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:armhf
    restart: always
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /whatever/path/openvpn:/vpn:ro
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    environment:
      - FIREWALL
    ports:
      - "8080:8080"

  joal:
    depends_on:
      - vpn
    container_name: joal
    image: anthonyraymond/joal:2.1.20
    restart: always
    network_mode: "service:vpn"
    volumes:
      - /whatever/path/joal:/data
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=8080", "--joal.ui.path.prefix=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "--joal.ui.secret-token=YYYYYYYYYYYYYYYYYYYYYYYY"]
    logging:
      options:
        max-size: "2m"
        max-file: "3"
```

The important part is the **network_mode: "service:vpn"** and the ports being mapped on the vpn container.
